name = "OptimizationCustomMethods"
uuid = "b32a464b-a62b-4abd-95f6-6c146489ffd8"
version = "0.1.0"
authors = ["Afonso Lamelas <alamelas@ua.pt>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OptimizationBase = "bca83a33-5cc9-4baa-983d-23429ab6bcbb"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
LinearAlgebra = "1.12.0"
OptimizationBase = "4.0.2"
QuasiMonteCarlo = "0.3.3"
Random = "1.11.0"
SciMLBase = "2.128.0"
SparseArrays = "1.12.0"
SpecialFunctions = "2.6.1"
Statistics = "1.11.1"
